import type { Chapter, Course, Topic } from "./schema";

export const courses: Course[] = [
  {
    id: "c-m4",
    slug: "m4",
    title: "คณิตศาสตร์ ม.4",
    level: "m4",
    description: "เซต ตรรกศาสตร์ จำนวนจริง ฟังก์ชัน และเรขาคณิตวิเคราะห์ — รากฐานของทุกอย่างที่ตามมา",
    order: 1,
  },
  {
    id: "c-m5",
    slug: "m5",
    title: "คณิตศาสตร์ ม.5",
    level: "m5",
    description: "ตรีโกณมิติ เวกเตอร์ เมทริกซ์ จำนวนเชิงซ้อน และสถิติ",
    order: 2,
  },
  {
    id: "c-m6",
    slug: "m6",
    title: "คณิตศาสตร์ ม.6",
    level: "m6",
    description: "ลิมิต ความต่อเนื่อง อนุพันธ์ และปริพันธ์ — ประตูสู่คณิตศาสตร์มหาวิทยาลัย",
    order: 3,
  },
];

export const chapters: Chapter[] = [
  { id: "ch-set", courseId: "c-m4", title: "เซต", order: 1 },
  { id: "ch-logic", courseId: "c-m4", title: "ตรรกศาสตร์", order: 2 },
  { id: "ch-real", courseId: "c-m4", title: "จำนวนจริง", order: 3 },
  { id: "ch-poly", courseId: "c-m4", title: "พหุนาม", order: 4 },
  { id: "ch-eq", courseId: "c-m4", title: "สมการและอสมการ", order: 5 },
  { id: "ch-func", courseId: "c-m4", title: "ฟังก์ชัน", order: 6 },
  { id: "ch-exp", courseId: "c-m4", title: "เอกซ์โพเนนเชียลและลอการิทึม", order: 7 },
  { id: "ch-geom", courseId: "c-m4", title: "เรขาคณิตวิเคราะห์", order: 8 },
  { id: "ch-seq", courseId: "c-m4", title: "ลำดับและอนุกรม", order: 9 },
  { id: "ch-count", courseId: "c-m4", title: "หลักการนับ", order: 10 },
  { id: "ch-prob", courseId: "c-m4", title: "ความน่าจะเป็น", order: 11 },
  { id: "ch-trig", courseId: "c-m5", title: "ตรีโกณมิติ", order: 1 },
  { id: "ch-vector", courseId: "c-m5", title: "เวกเตอร์", order: 2 },
  { id: "ch-complex", courseId: "c-m5", title: "จำนวนเชิงซ้อน", order: 3 },
  { id: "ch-matrix", courseId: "c-m5", title: "เมทริกซ์", order: 4 },
  { id: "ch-stat", courseId: "c-m5", title: "สถิติ", order: 5 },
  { id: "ch-limit", courseId: "c-m6", title: "ลิมิตและความต่อเนื่อง", order: 1 },
  { id: "ch-deriv", courseId: "c-m6", title: "อนุพันธ์", order: 2 },
  { id: "ch-integral", courseId: "c-m6", title: "ปริพันธ์", order: 3 },
];

export const topics: Topic[] = [
  {
    id: "t-set-basic",
    chapterId: "ch-set",
    slug: "set-basic",
    title: "ความหมายและการเขียนเซต",
    summary: "เซตคืออะไร เขียนอย่างไร และทำไมคณิตศาสตร์ทั้งหมดจึงสร้างอยู่บนแนวคิดนี้",
    order: 1,
    prerequisites: [],
  },
  {
    id: "t-real-line",
    chapterId: "ch-real",
    slug: "real-number-line",
    title: "จำนวนจริงและเส้นจำนวน",
    summary: "ช่วง ค่าสัมบูรณ์ และการอ่านเซตคำตอบจากเส้นจำนวน",
    order: 1,
    prerequisites: ["t-set-basic"],
  },
  {
    id: "t-function",
    chapterId: "ch-func",
    slug: "function-basic",
    title: "ฟังก์ชันคืออะไร",
    summary: "โดเมน เรนจ์ และเงื่อนไขข้อเดียวที่แยกฟังก์ชันออกจากความสัมพันธ์ทั่วไป",
    order: 1,
    prerequisites: ["t-set-basic", "t-real-line"],
  },
  {
    id: "t-quadratic",
    chapterId: "ch-func",
    slug: "quadratic-function",
    title: "ฟังก์ชันกำลังสอง",
    summary: "พาราโบลา จุดยอด แกนสมมาตร และความหมายของ b² − 4ac",
    order: 2,
    prerequisites: ["t-function"],
  },
  {
    id: "t-logic",
    chapterId: "ch-logic",
    slug: "logic-basic",
    title: "ตรรกศาสตร์เบื้องต้น",
    summary: "ประพจน์ ตัวเชื่อม ตารางค่าความจริง สมมูล และการอ้างเหตุผล",
    order: 1,
    prerequisites: ["t-set-basic"],
  },
  {
    id: "t-polynomial",
    chapterId: "ch-poly",
    slug: "polynomial",
    title: "พหุนามและการแยกตัวประกอบ",
    summary: "ดีกรี การหารพหุนาม ทฤษฎีบทเศษเหลือ ทฤษฎีบทตัวประกอบ และเทคนิคแยกตัวประกอบ",
    order: 1,
    prerequisites: ["t-real-line"],
  },
  {
    id: "t-equation",
    chapterId: "ch-eq",
    slug: "equation-inequality",
    title: "สมการและอสมการ",
    summary: "สมการพหุนาม สมการเศษส่วน สมการติดราก และการแก้อสมการทุกแบบด้วยเส้นจำนวน",
    order: 1,
    prerequisites: ["t-polynomial", "t-real-line"],
  },
  {
    id: "t-exponential",
    chapterId: "ch-exp",
    slug: "exponential",
    title: "ฟังก์ชันเอกซ์โพเนนเชียล",
    summary: "เลขยกกำลัง สมบัติ กราฟการเติบโตและการสลายตัว และการแก้สมการเอกซ์โพเนนเชียล",
    order: 1,
    prerequisites: ["t-function"],
  },
  {
    id: "t-logarithm",
    chapterId: "ch-exp",
    slug: "logarithm",
    title: "ลอการิทึม",
    summary: "ความหมาย สมบัติของลอการิทึม การเปลี่ยนฐาน กราฟ และการแก้สมการ",
    order: 2,
    prerequisites: ["t-exponential"],
  },
  {
    id: "t-analytic",
    chapterId: "ch-geom",
    slug: "analytic-geometry",
    title: "เรขาคณิตวิเคราะห์",
    summary: "ระยะทาง จุดกึ่งกลาง ความชัน สมการเส้นตรง และสมการวงกลม",
    order: 1,
    prerequisites: ["t-function", "t-real-line"],
  },
  {
    id: "t-sequence",
    chapterId: "ch-seq",
    slug: "sequence-series",
    title: "ลำดับและอนุกรม",
    summary: "ลำดับเลขคณิต ลำดับเรขาคณิต ผลบวก n พจน์แรก และสัญลักษณ์ซิกมา",
    order: 1,
    prerequisites: ["t-function"],
  },
  {
    id: "t-counting",
    chapterId: "ch-count",
    slug: "counting",
    title: "หลักการนับ",
    summary: "กฎการบวก กฎการคูณ การเรียงสับเปลี่ยน และการจัดหมู่",
    order: 1,
    prerequisites: ["t-set-basic"],
  },
  {
    id: "t-probability",
    chapterId: "ch-prob",
    slug: "probability",
    title: "ความน่าจะเป็น",
    summary: "การทดลองสุ่ม แซมเปิลสเปซ เหตุการณ์ และการคำนวณความน่าจะเป็น",
    order: 1,
    prerequisites: ["t-counting", "t-set-basic"],
  },
  {
    id: "t-unit-circle",
    chapterId: "ch-trig",
    slug: "unit-circle",
    title: "วงกลมหนึ่งหน่วย",
    summary: "นิยาม sin cos tan ที่ใช้ได้กับทุกมุม ไม่ใช่แค่มุมในสามเหลี่ยมมุมฉาก",
    order: 1,
    prerequisites: ["t-function"],
  },
  {
    id: "t-trig-identity",
    chapterId: "ch-trig",
    slug: "trig-identity",
    title: "เอกลักษณ์ตรีโกณมิติและสมการตรีโกณ",
    summary: "เอกลักษณ์พีทาโกรัส สูตรผลบวกมุม มุมสองเท่า การพิสูจน์เอกลักษณ์ และการแก้สมการตรีโกณ",
    order: 2,
    prerequisites: ["t-unit-circle"],
  },
  {
    id: "t-trig-law",
    chapterId: "ch-trig",
    slug: "trig-law",
    title: "กฎไซน์และกฎโคไซน์",
    summary: "แก้สามเหลี่ยมที่ไม่มีมุมฉาก สูตรพื้นที่ สูตรเฮรอน กรณีคลุมเครือ และโจทย์ประยุกต์",
    order: 3,
    prerequisites: ["t-trig-identity"],
  },
  {
    id: "t-matrix",
    chapterId: "ch-matrix",
    slug: "matrix",
    title: "เมทริกซ์",
    summary: "การดำเนินการ ดีเทอร์มิแนนต์ อินเวอร์ส กฎของคราเมอร์ และการแก้ระบบสมการเชิงเส้น",
    order: 1,
    prerequisites: ["t-equation"],
  },
  {
    id: "t-vector",
    chapterId: "ch-vector",
    slug: "vector",
    title: "เวกเตอร์",
    summary: "ขนาดและทิศทาง ส่วนประกอบ การบวกลบ ผลคูณจุด มุมระหว่างเวกเตอร์ และส่วนฉาย",
    order: 1,
    prerequisites: ["t-unit-circle", "t-analytic"],
  },
  {
    id: "t-complex",
    chapterId: "ch-complex",
    slug: "complex-number",
    title: "จำนวนเชิงซ้อน",
    summary: "หน่วยจินตภาพ การดำเนินการ ระนาบเชิงซ้อน โมดูลัส รูปเชิงขั้ว และทฤษฎีบทเดอมัวฟร์",
    order: 1,
    prerequisites: ["t-unit-circle", "t-polynomial"],
  },
  {
    id: "t-statistics",
    chapterId: "ch-stat",
    slug: "statistics",
    title: "สถิติเชิงพรรณนา",
    summary: "ค่ากลาง การกระจาย ควอร์ไทล์ แผนภาพกล่อง และการเลือกใช้ค่าสถิติให้เหมาะกับข้อมูล",
    order: 1,
    prerequisites: ["t-real-line"],
  },
  {
    id: "t-limit",
    chapterId: "ch-limit",
    slug: "limit-continuity",
    title: "ลิมิตและความต่อเนื่อง",
    summary: "ความหมายของการเข้าใกล้ ลิมิตซ้ายขวา เทคนิคจัดการรูปแบบ 0/0 และเงื่อนไขสามข้อของความต่อเนื่อง",
    order: 1,
    prerequisites: ["t-function", "t-equation"],
  },
  {
    id: "t-derivative",
    chapterId: "ch-deriv",
    slug: "derivative-intro",
    title: "อนุพันธ์คืออะไร",
    summary: "จากความชันของเส้นตัด สู่ความชันที่จุดเดียว เมื่อ Δx → 0",
    order: 1,
    prerequisites: ["t-function", "t-quadratic", "t-limit"],
  },
  {
    id: "t-deriv-app",
    chapterId: "ch-deriv",
    slug: "derivative-application",
    title: "การประยุกต์อนุพันธ์",
    summary: "ช่วงเพิ่มลด จุดสูงสุด–ต่ำสุด ความเว้า การเขียนกราฟ โจทย์ค่าเหมาะที่สุด และอัตราสัมพัทธ์",
    order: 2,
    prerequisites: ["t-derivative"],
  },
  {
    id: "t-integral",
    chapterId: "ch-integral",
    slug: "integral",
    title: "ปริพันธ์",
    summary: "ปฏิยานุพันธ์ ทฤษฎีบทหลักมูลของแคลคูลัส พื้นที่ใต้กราฟ และการหาปริมาณสะสมจากอัตราการเปลี่ยนแปลง",
    order: 1,
    prerequisites: ["t-derivative"],
  },
];
